name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executes every 12 hours
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write  # Permission to write to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure the repository is checked out

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ro4dy5alifa  # Replace with your GitHub username
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Ensure this branch exists
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the correct secret reference
